name: CI Build, Test & Docker Build

on:
  push:
    branches:
      - beaus-dev
    paths:
      - 'beaus/auth-service/**'
      - 'beaus/pom.xml'
  pull_request:
    branches:
      - beaus-dev
    paths:
      - 'beaus/auth-service/**'
      - 'beaus/pom.xml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Maven Packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('beaus/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build Auth Service
        working-directory: beaus/auth-service
        run: mvn clean package

      #- name: Build Docker Image for Auth Service
      #  working-directory: beaus/auth-service
      #  run: |
        #  docker build -t my-auth-service:latest .
